const IDLE_WINDOW_ASSET_BASE = 'assets/personal-space/idle-window';

export const idleWindowAssetRegistry = {
  backgrounds: {
    'survival-rental-left': {
      id: 'survival-rental-left',
      label: 'Survival Rental Left',
      type: 'background',
      stage: 'survival',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/survival-rental-left.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'survival-rental-center': {
      id: 'survival-rental-center',
      label: 'Survival Rental Center',
      type: 'background',
      stage: 'survival',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/survival-rental-center.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'survival-rental-right': {
      id: 'survival-rental-right',
      label: 'Survival Rental Right',
      type: 'background',
      stage: 'survival',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/survival-rental-right.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'office-angle-left-v2': {
      id: 'office-angle-left-v2',
      label: 'Office Angle Left V2',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-angle-left-v2.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'office-angle-center-v2': {
      id: 'office-angle-center-v2',
      label: 'Office Angle Center V2',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-angle-center-v2.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'office-angle-right-v2': {
      id: 'office-angle-right-v2',
      label: 'Office Angle Right V2',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-angle-right-v2.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'office-angle-overhead-proof': {
      id: 'office-angle-overhead-proof',
      label: 'Office Angle Overhead Proof',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'angle-proof',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-angle-overhead-proof.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'reference-angle-proof',
    },
    'mastery-estate-left': {
      id: 'mastery-estate-left',
      label: 'Mastery Estate Left',
      type: 'background',
      stage: 'mastery',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/mastery-estate-left.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'mastery-estate-center': {
      id: 'mastery-estate-center',
      label: 'Mastery Estate Center',
      type: 'background',
      stage: 'mastery',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/mastery-estate-center.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'mastery-estate-right': {
      id: 'mastery-estate-right',
      label: 'Mastery Estate Right',
      type: 'background',
      stage: 'mastery',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/mastery-estate-right.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'production-background',
    },
    'office-angle-left': {
      id: 'office-angle-left',
      label: 'Office Angle Left',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-angle-left.png`,
      dimensions: { width: 721, height: 483 },
      status: 'production-proof',
    },
    'office-angle-center': {
      id: 'office-angle-center',
      label: 'Office Angle Center',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-angle-center.png`,
      dimensions: { width: 723, height: 483 },
      status: 'production-proof',
    },
    'office-angle-right': {
      id: 'office-angle-right',
      label: 'Office Angle Right',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'camera-profile',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-angle-right.png`,
      dimensions: { width: 719, height: 483 },
      status: 'production-proof',
    },
    'office-idle-window-base': {
      id: 'office-idle-window-base',
      label: 'Office Idle Window Base',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'stage-base',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-idle-window-base.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'clean-base',
    },
    'office-idle-window-concept': {
      id: 'office-idle-window-concept',
      label: 'Office Idle Window Concept',
      type: 'background',
      stage: 'building',
      runtime: 'image',
      role: 'art-direction',
      path: `${IDLE_WINDOW_ASSET_BASE}/backgrounds/office-idle-window-concept.png`,
      dimensions: { width: 1672, height: 941 },
      status: 'concept-reference',
    },
  },
  props: {
    'office-leather-sofa': buildPropAsset({
      id: 'office-leather-sofa',
      label: 'Leather Lounge Sofa',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-leather-sofa/prop.png`,
      dimensions: { width: 426, height: 251 },
      source: 'office-leather-sofa-variant-sheet-v1',
      qc: 'passed',
      variants: [
        variant('front', 'Front', {
          path: `${IDLE_WINDOW_ASSET_BASE}/props/office-leather-sofa/prop.png`,
          dimensions: { width: 426, height: 251 },
          cameraProfileId: 'center',
          status: 'perspective-correct',
        }),
        variant('left-wall-flush', 'Left wall flush', {
          path: `${IDLE_WINDOW_ASSET_BASE}/props/office-leather-sofa/left-wall-flush.png`,
          dimensions: { width: 535, height: 323 },
          cameraProfileId: 'left',
          status: 'perspective-correct',
        }),
        variant('right-wall-flush', 'Right wall flush', {
          path: `${IDLE_WINDOW_ASSET_BASE}/props/office-leather-sofa/right-wall-flush.png`,
          dimensions: { width: 558, height: 323 },
          cameraProfileId: 'right',
          status: 'perspective-correct',
        }),
      ],
    }),
    'office-low-coffee-table': buildPropAsset({
      id: 'office-low-coffee-table',
      label: 'Low Coffee Table',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-low-coffee-table/prop.png`,
      dimensions: { width: 353, height: 218 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-filing-cabinet': buildPropAsset({
      id: 'office-filing-cabinet',
      label: 'Filing Cabinet',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-filing-cabinet/prop.png`,
      dimensions: { width: 198, height: 303 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-trophy-display': buildPropAsset({
      id: 'office-trophy-display',
      label: 'Trophy Display Cabinet',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-trophy-display/prop.png`,
      dimensions: { width: 305, height: 302 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-achievement-board': buildPropAsset({
      id: 'office-achievement-board',
      label: 'Achievement Board',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-achievement-board/prop.png`,
      dimensions: { width: 305, height: 256 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-floor-lamp': buildPropAsset({
      id: 'office-floor-lamp',
      label: 'Floor Lamp',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-floor-lamp/prop.png`,
      dimensions: { width: 130, height: 320 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-pattern-rug': buildPropAsset({
      id: 'office-pattern-rug',
      label: 'Patterned Office Rug',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-pattern-rug/prop.png`,
      dimensions: { width: 460, height: 176 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-side-table': buildPropAsset({
      id: 'office-side-table',
      label: 'Office Side Table',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-side-table/prop.png`,
      dimensions: { width: 370, height: 234 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-mountain-wall-art': buildPropAsset({
      id: 'office-mountain-wall-art',
      label: 'Mountain Wall Art',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-mountain-wall-art/prop.png`,
      dimensions: { width: 234, height: 249 },
      source: 'office-expansion-furniture-sheet',
      qc: 'passed',
    }),
    'office-open-notebook': buildPropAsset({
      id: 'office-open-notebook',
      label: 'Open Notebook',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-open-notebook/prop.png`,
      dimensions: { width: 370, height: 237 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-book-stack': buildPropAsset({
      id: 'office-book-stack',
      label: 'Book Stack',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-book-stack/prop.png`,
      dimensions: { width: 304, height: 278 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-brass-desk-clock': buildPropAsset({
      id: 'office-brass-desk-clock',
      label: 'Brass Desk Clock',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-brass-desk-clock/prop.png`,
      dimensions: { width: 256, height: 301 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-framed-photo': buildPropAsset({
      id: 'office-framed-photo',
      label: 'Framed Photo',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-framed-photo/prop.png`,
      dimensions: { width: 248, height: 302 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-tea-cup-saucer': buildPropAsset({
      id: 'office-tea-cup-saucer',
      label: 'Tea Cup And Saucer',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-tea-cup-saucer/prop.png`,
      dimensions: { width: 303, height: 232 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-potted-succulent': buildPropAsset({
      id: 'office-potted-succulent',
      label: 'Potted Succulent',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-potted-succulent/prop.png`,
      dimensions: { width: 220, height: 257 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-folded-blueprint': buildPropAsset({
      id: 'office-folded-blueprint',
      label: 'Folded Blueprint',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-folded-blueprint/prop.png`,
      dimensions: { width: 372, height: 257 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-tiny-trophy': buildPropAsset({
      id: 'office-tiny-trophy',
      label: 'Tiny Trophy',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-tiny-trophy/prop.png`,
      dimensions: { width: 201, height: 256 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-leather-journal': buildPropAsset({
      id: 'office-leather-journal',
      label: 'Leather Journal',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-leather-journal/prop.png`,
      dimensions: { width: 328, height: 255 },
      source: 'office-growth-small-props-sheet',
      qc: 'passed',
    }),
    'office-tall-bookcase': buildPropAsset({
      id: 'office-tall-bookcase',
      label: 'Tall Bookcase',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-tall-bookcase/prop.png`,
      dimensions: { width: 227, height: 328 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-floating-shelf': buildPropAsset({
      id: 'office-floating-shelf',
      label: 'Floating Shelf',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-floating-shelf/prop.png`,
      dimensions: { width: 377, height: 234 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-cork-planning-board': buildPropAsset({
      id: 'office-cork-planning-board',
      label: 'Cork Planning Board',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-cork-planning-board/prop.png`,
      dimensions: { width: 345, height: 253 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-window-bench': buildPropAsset({
      id: 'office-window-bench',
      label: 'Window Bench',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-window-bench/prop.png`,
      dimensions: { width: 415, height: 326 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-coat-rack': buildPropAsset({
      id: 'office-coat-rack',
      label: 'Coat Rack',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-coat-rack/prop.png`,
      dimensions: { width: 134, height: 318 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-printer-cabinet': buildPropAsset({
      id: 'office-printer-cabinet',
      label: 'Printer Cabinet',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-printer-cabinet/prop.png`,
      dimensions: { width: 279, height: 306 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-city-map-frame': buildPropAsset({
      id: 'office-city-map-frame',
      label: 'City Map Frame',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-city-map-frame/prop.png`,
      dimensions: { width: 317, height: 259 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-wall-sconce': buildPropAsset({
      id: 'office-wall-sconce',
      label: 'Wall Sconce',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-wall-sconce/prop.png`,
      dimensions: { width: 205, height: 224 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-document-safe': buildPropAsset({
      id: 'office-document-safe',
      label: 'Document Safe',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-document-safe/prop.png`,
      dimensions: { width: 248, height: 299 },
      source: 'office-wall-storage-sheet',
      qc: 'passed',
    }),
    'office-corner-desk-v3': buildPropAsset({
      id: 'office-corner-desk-v3',
      label: 'Office Corner Desk V3',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-corner-desk-v3/front.png`,
      dimensions: { width: 524, height: 302 },
      source: 'direction-variant-sheet',
      qc: 'passed',
      variants: [
        variant('front', 'Front', {
          path: `${IDLE_WINDOW_ASSET_BASE}/props/office-corner-desk-v3/front.png`,
          dimensions: { width: 524, height: 302 },
          cameraProfileId: 'center',
          status: 'perspective-correct',
        }),
        variant('left-wall-flush', 'Left wall flush', {
          path: `${IDLE_WINDOW_ASSET_BASE}/props/office-corner-desk-v3/left-wall-flush.png`,
          dimensions: { width: 592, height: 366 },
          cameraProfileId: 'left',
          status: 'perspective-correct',
        }),
        variant('right-wall-flush', 'Right wall flush', {
          path: `${IDLE_WINDOW_ASSET_BASE}/props/office-corner-desk-v3/right-wall-flush.png`,
          dimensions: { width: 591, height: 366 },
          cameraProfileId: 'right',
          status: 'perspective-correct',
        }),
      ],
    }),
    'office-corner-desk-v2': buildPropAsset({
      id: 'office-corner-desk-v2',
      label: 'Office Corner Desk V2',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-corner-desk-v2/office-corner-desk-v2-1.png`,
      dimensions: { width: 512, height: 512 },
      source: 'one-by-one',
      qc: 'passed',
      variants: [
        variant('front', 'Front'),
        variant('left-wall-flush', 'Left wall flush', { status: 'needs-generated-perspective-art' }),
        variant('right-wall-flush', 'Right wall flush', { flipX: true, status: 'prototype-mirror' }),
      ],
    }),
    'office-chair': buildPropAsset({
      id: 'office-chair',
      label: 'Office Chair',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-chair/prop.png`,
      dimensions: { width: 188, height: 321 },
      source: 'office-prop-pack',
      qc: 'passed',
    }),
    'office-monitor-single': buildPropAsset({
      id: 'office-monitor-single',
      label: 'Single Monitor',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-monitor-single/prop.png`,
      dimensions: { width: 222, height: 259 },
      source: 'office-prop-pack',
      qc: 'passed',
      variants: [
        variant('front', 'Front'),
        variant('mirror-test', 'Mirror test', { flipX: true, status: 'prototype-mirror' }),
      ],
    }),
    'office-monitor-dual': buildPropAsset({
      id: 'office-monitor-dual',
      label: 'Dual Monitor',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-monitor-dual/prop.png`,
      dimensions: { width: 330, height: 266 },
      source: 'office-prop-pack',
      qc: 'passed',
    }),
    'office-shelf': buildPropAsset({
      id: 'office-shelf',
      label: 'Office Shelf',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-shelf/prop.png`,
      dimensions: { width: 265, height: 350 },
      source: 'office-prop-pack',
      qc: 'passed',
      variants: [
        variant('front', 'Front'),
        variant('mirror-test', 'Mirror test', { flipX: true, status: 'prototype-mirror' }),
      ],
    }),
    'office-plant': buildPropAsset({
      id: 'office-plant',
      label: 'Office Plant',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-plant/prop.png`,
      dimensions: { width: 233, height: 300 },
      source: 'office-prop-pack',
      qc: 'passed',
    }),
    'office-board': buildPropAsset({
      id: 'office-board',
      label: 'Office Board',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-board/prop.png`,
      dimensions: { width: 311, height: 248 },
      source: 'office-prop-pack',
      qc: 'passed',
    }),
    'office-desk-lamp': buildPropAsset({
      id: 'office-desk-lamp',
      label: 'Office Desk Lamp',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-desk-lamp/prop.png`,
      dimensions: { width: 197, height: 280 },
      source: 'office-prop-pack',
      qc: 'passed',
      variants: [
        variant('front', 'Front'),
        variant('mirror-test', 'Mirror test', { flipX: true, status: 'prototype-mirror' }),
      ],
    }),
    'office-coffee-cup': buildPropAsset({
      id: 'office-coffee-cup',
      label: 'Office Coffee Cup',
      path: `${IDLE_WINDOW_ASSET_BASE}/props/office-coffee-cup/prop.png`,
      dimensions: { width: 213, height: 270 },
      source: 'office-prop-pack',
      qc: 'passed',
      variants: [
        variant('front', 'Front'),
        variant('mirror-test', 'Mirror test', { flipX: true, status: 'prototype-mirror' }),
      ],
    }),
  },
  characters: {
    'building-protagonist-idle': {
      id: 'building-protagonist-idle',
      label: 'Building Stage Protagonist Idle',
      type: 'character',
      stage: 'building',
      runtime: 'sprite-sheet',
      path: `${IDLE_WINDOW_ASSET_BASE}/characters/building-protagonist-idle/sheet-transparent.png`,
      previewPath: `${IDLE_WINDOW_ASSET_BASE}/characters/building-protagonist-idle/animation.gif`,
      framePaths: [
        `${IDLE_WINDOW_ASSET_BASE}/characters/building-protagonist-idle/building-protagonist-idle-1.png`,
        `${IDLE_WINDOW_ASSET_BASE}/characters/building-protagonist-idle/building-protagonist-idle-2.png`,
        `${IDLE_WINDOW_ASSET_BASE}/characters/building-protagonist-idle/building-protagonist-idle-3.png`,
        `${IDLE_WINDOW_ASSET_BASE}/characters/building-protagonist-idle/building-protagonist-idle-4.png`,
      ],
      sheet: {
        rows: 2,
        cols: 2,
        frameWidth: 128,
        frameHeight: 128,
        durationMs: 240,
      },
      anchor: 'feet',
      qc: 'passed',
    },
  },
};

export function getIdleWindowAsset(collection, assetId) {
  return idleWindowAssetRegistry[collection]?.[assetId] || null;
}

export function getIdleWindowBackground(assetId) {
  return getIdleWindowAsset('backgrounds', assetId);
}

export function getIdleWindowProp(assetId) {
  return getIdleWindowAsset('props', assetId);
}

export function getIdleWindowCharacter(assetId) {
  return getIdleWindowAsset('characters', assetId);
}

function buildPropAsset({ id, label, path, dimensions, source, qc, variants }) {
  return {
    id,
    label,
    type: 'prop',
    runtime: 'image',
    path,
    dimensions,
    source,
    qc,
    variants: normalizeVariants({ path, dimensions, variants }),
  };
}

function variant(id, label, options = {}) {
  return {
    id,
    label,
    ...options,
  };
}

function normalizeVariants({ path, dimensions, variants }) {
  const entries = Array.isArray(variants) && variants.length
    ? variants
    : [variant('front', 'Front')];

  return entries.map(entry => ({
    id: entry.id,
    label: entry.label || entry.id,
    path: entry.path || path,
    dimensions: entry.dimensions || dimensions,
    flipX: Boolean(entry.flipX),
    cameraProfileId: entry.cameraProfileId || null,
    status: entry.status || 'source',
  }));
}
